import { Entity, Schema } from 'redis-om';

// Define an interface for User
export interface IUser {
  id?: string; // Optional, generated by Redis
  username: string;
  password: string;
  email: string;
  role: string;
  company?: string; // Nullable
  branch?: string;  // Nullable
  phone: string;
}

// Extend User class with the IUser interface
export class User  implements IUser {
  username!: string;
  password!: string;
  email!: string;
  role!: string;
  company?: string;
  branch?: string;
  phone!: string;
}

// Define the schema for the user model
export const userSchema = new Schema('User', {
  username: { type: 'string' },
  password: { type: 'string' },
  email: { type: 'string' },
  role: { type: 'string' },
  company: { type: 'string',  },
  branch: { type: 'string' },
  phone: { type: 'string' },
});

export default userSchema